# Build rule
[build]
  command = "npm run build"
  publish = "/build"
  functions = "./functions"

# Redirects rule
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Development rule
[dev]
  command = "npm start"
  port = 8888
  targetPort = 3000
